#!/usr/bin/python
# Author        Josef Zacharias
# Link          https://linkedin.com/in/jzacharias
# Created       Oct 05, 2017
# Copyright     (c) 2017

---
- hosts: [Testservers]
  remote_user: root
  tasks:

## OS preparation

    - name: Update OS to latest version
      yum:
        update_cache: yes
        name: "*"
        state: latest

    - name: Add repo for MariaDB
      yum_repository:
         name: MariaDB
         description: MariaDB repo
         file: mariaDB.repo
         baseurl: http://yum.mariadb.org/10.2/centos7-amd64
         gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
         gpgcheck: yes

## Install and uninstall packages via yum

    - name: Install basic packages
      yum:
        name: "{{ item }}"
        state: latest
        
      with_items:
        - mc
        - wget
        - MariaDB-server
        - MariaDB-client
        - screen
        - iptables-services
        - unzip
        - sudo
        - MySQL-python
        - http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm
        - zabbix-agent
        - showmount

    - name: Uninstall unnecessary packages
      yum:
        name: "{{ item }}"
        state: absent

      with_items:
        - postfix
        - firewalld
        - Network-Manager*

    - name: Start MySQL
      service:
        name: mysql
        state: started

## Set security options, set firewall rules

    - name: Disable SELinux
      selinux:
        state: permissive
        policy: targetted

#    - name: Allow TCP 80 and 443
#      command: /sbin/iptables -I INPUT 1 -p tcp --dport "{{ item }}" -j ACCEPT -m comment --comment "IceWarp WebClient"
#      with_items:
#         - http
#         - https

#     - set_fact:
#       restart_iptables: 0
#    - iptables:
#        chain: INPUT
#        destination_port: "{{ item  }}"
#        jump: ACCEPT
#        protocol: tcp
#      with_items:
#        - 22
#        - 80
#        - 443
#        - 25
#        - 143
#        - 993
#        - 465
#        - 110
#        - 995
#       register: fw_rules
#
#    - set_fact:
#      restart_iptables: 1
#      when: fw_rules.changed
#
#    - iptables:
#       chain: INPUT
#        jump: ACCEPT
#        ctstate: ESTABLISHED,RELATED
#      register: fw_rules

#    - set_fact:
#      restart_iptables: 1
#      when: fw_rules.changed

#    - iptables:
#        chain: OUTPUT
#        policy: ACCEPT
#      register: fw_rules

#    - set_fact:
#      restart_iptables: 1
#      when: fw_rules.changed
#
#    - name: Firewall rule - drop any traffic without rule
#      iptables:
#        chain: INPUT
#        jump: DROP
#      register: fw_rules

#    - set_fact:
#      restart_iptables: 1
#      when: fw_rules.changed

#    - block:       
#      - name: Save iptables
#        command: service iptables save
#        when: restart_iptables == 1
#
#      - name: Restart iptables
#        service:
#          name: iptables
#          state: restarted
#        when: restart_iptables == 1
